# Generated by Django 6.0.4 on 2026-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_preview_alter_lesson_video_link"),
        ("materials", "0003_course_updated_at"),
    ]

    operations = []
